// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/opinion/rules/RuleResult.proto

package proto;

public final class RuleResultOuterClass {
  private RuleResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RuleResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RuleResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.RuleDescription rule_description = 1;</code>
     */
    boolean hasRuleDescription();
    /**
     * <code>.proto.RuleDescription rule_description = 1;</code>
     */
    proto.RuleResultOuterClass.RuleDescription getRuleDescription();
    /**
     * <code>.proto.RuleDescription rule_description = 1;</code>
     */
    proto.RuleResultOuterClass.RuleDescriptionOrBuilder getRuleDescriptionOrBuilder();

    /**
     * <code>bool rule_applies = 2;</code>
     */
    boolean getRuleApplies();
  }
  /**
   * Protobuf type {@code proto.RuleResult}
   */
  public  static final class RuleResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.RuleResult)
      RuleResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RuleResult.newBuilder() to construct.
    private RuleResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RuleResult() {
      ruleApplies_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RuleResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              proto.RuleResultOuterClass.RuleDescription.Builder subBuilder = null;
              if (ruleDescription_ != null) {
                subBuilder = ruleDescription_.toBuilder();
              }
              ruleDescription_ = input.readMessage(proto.RuleResultOuterClass.RuleDescription.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ruleDescription_);
                ruleDescription_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              ruleApplies_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RuleResultOuterClass.internal_static_proto_RuleResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RuleResultOuterClass.internal_static_proto_RuleResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RuleResultOuterClass.RuleResult.class, proto.RuleResultOuterClass.RuleResult.Builder.class);
    }

    public static final int RULE_DESCRIPTION_FIELD_NUMBER = 1;
    private proto.RuleResultOuterClass.RuleDescription ruleDescription_;
    /**
     * <code>.proto.RuleDescription rule_description = 1;</code>
     */
    public boolean hasRuleDescription() {
      return ruleDescription_ != null;
    }
    /**
     * <code>.proto.RuleDescription rule_description = 1;</code>
     */
    public proto.RuleResultOuterClass.RuleDescription getRuleDescription() {
      return ruleDescription_ == null ? proto.RuleResultOuterClass.RuleDescription.getDefaultInstance() : ruleDescription_;
    }
    /**
     * <code>.proto.RuleDescription rule_description = 1;</code>
     */
    public proto.RuleResultOuterClass.RuleDescriptionOrBuilder getRuleDescriptionOrBuilder() {
      return getRuleDescription();
    }

    public static final int RULE_APPLIES_FIELD_NUMBER = 2;
    private boolean ruleApplies_;
    /**
     * <code>bool rule_applies = 2;</code>
     */
    public boolean getRuleApplies() {
      return ruleApplies_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ruleDescription_ != null) {
        output.writeMessage(1, getRuleDescription());
      }
      if (ruleApplies_ != false) {
        output.writeBool(2, ruleApplies_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ruleDescription_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRuleDescription());
      }
      if (ruleApplies_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, ruleApplies_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RuleResultOuterClass.RuleResult)) {
        return super.equals(obj);
      }
      proto.RuleResultOuterClass.RuleResult other = (proto.RuleResultOuterClass.RuleResult) obj;

      boolean result = true;
      result = result && (hasRuleDescription() == other.hasRuleDescription());
      if (hasRuleDescription()) {
        result = result && getRuleDescription()
            .equals(other.getRuleDescription());
      }
      result = result && (getRuleApplies()
          == other.getRuleApplies());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRuleDescription()) {
        hash = (37 * hash) + RULE_DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getRuleDescription().hashCode();
      }
      hash = (37 * hash) + RULE_APPLIES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRuleApplies());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RuleResultOuterClass.RuleResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RuleResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RuleResult)
        proto.RuleResultOuterClass.RuleResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RuleResultOuterClass.RuleResult.class, proto.RuleResultOuterClass.RuleResult.Builder.class);
      }

      // Construct using proto.RuleResultOuterClass.RuleResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (ruleDescriptionBuilder_ == null) {
          ruleDescription_ = null;
        } else {
          ruleDescription_ = null;
          ruleDescriptionBuilder_ = null;
        }
        ruleApplies_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleResult_descriptor;
      }

      public proto.RuleResultOuterClass.RuleResult getDefaultInstanceForType() {
        return proto.RuleResultOuterClass.RuleResult.getDefaultInstance();
      }

      public proto.RuleResultOuterClass.RuleResult build() {
        proto.RuleResultOuterClass.RuleResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RuleResultOuterClass.RuleResult buildPartial() {
        proto.RuleResultOuterClass.RuleResult result = new proto.RuleResultOuterClass.RuleResult(this);
        if (ruleDescriptionBuilder_ == null) {
          result.ruleDescription_ = ruleDescription_;
        } else {
          result.ruleDescription_ = ruleDescriptionBuilder_.build();
        }
        result.ruleApplies_ = ruleApplies_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RuleResultOuterClass.RuleResult) {
          return mergeFrom((proto.RuleResultOuterClass.RuleResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RuleResultOuterClass.RuleResult other) {
        if (other == proto.RuleResultOuterClass.RuleResult.getDefaultInstance()) return this;
        if (other.hasRuleDescription()) {
          mergeRuleDescription(other.getRuleDescription());
        }
        if (other.getRuleApplies() != false) {
          setRuleApplies(other.getRuleApplies());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RuleResultOuterClass.RuleResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RuleResultOuterClass.RuleResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private proto.RuleResultOuterClass.RuleDescription ruleDescription_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RuleResultOuterClass.RuleDescription, proto.RuleResultOuterClass.RuleDescription.Builder, proto.RuleResultOuterClass.RuleDescriptionOrBuilder> ruleDescriptionBuilder_;
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public boolean hasRuleDescription() {
        return ruleDescriptionBuilder_ != null || ruleDescription_ != null;
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public proto.RuleResultOuterClass.RuleDescription getRuleDescription() {
        if (ruleDescriptionBuilder_ == null) {
          return ruleDescription_ == null ? proto.RuleResultOuterClass.RuleDescription.getDefaultInstance() : ruleDescription_;
        } else {
          return ruleDescriptionBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public Builder setRuleDescription(proto.RuleResultOuterClass.RuleDescription value) {
        if (ruleDescriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ruleDescription_ = value;
          onChanged();
        } else {
          ruleDescriptionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public Builder setRuleDescription(
          proto.RuleResultOuterClass.RuleDescription.Builder builderForValue) {
        if (ruleDescriptionBuilder_ == null) {
          ruleDescription_ = builderForValue.build();
          onChanged();
        } else {
          ruleDescriptionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public Builder mergeRuleDescription(proto.RuleResultOuterClass.RuleDescription value) {
        if (ruleDescriptionBuilder_ == null) {
          if (ruleDescription_ != null) {
            ruleDescription_ =
              proto.RuleResultOuterClass.RuleDescription.newBuilder(ruleDescription_).mergeFrom(value).buildPartial();
          } else {
            ruleDescription_ = value;
          }
          onChanged();
        } else {
          ruleDescriptionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public Builder clearRuleDescription() {
        if (ruleDescriptionBuilder_ == null) {
          ruleDescription_ = null;
          onChanged();
        } else {
          ruleDescription_ = null;
          ruleDescriptionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public proto.RuleResultOuterClass.RuleDescription.Builder getRuleDescriptionBuilder() {
        
        onChanged();
        return getRuleDescriptionFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      public proto.RuleResultOuterClass.RuleDescriptionOrBuilder getRuleDescriptionOrBuilder() {
        if (ruleDescriptionBuilder_ != null) {
          return ruleDescriptionBuilder_.getMessageOrBuilder();
        } else {
          return ruleDescription_ == null ?
              proto.RuleResultOuterClass.RuleDescription.getDefaultInstance() : ruleDescription_;
        }
      }
      /**
       * <code>.proto.RuleDescription rule_description = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.RuleResultOuterClass.RuleDescription, proto.RuleResultOuterClass.RuleDescription.Builder, proto.RuleResultOuterClass.RuleDescriptionOrBuilder> 
          getRuleDescriptionFieldBuilder() {
        if (ruleDescriptionBuilder_ == null) {
          ruleDescriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.RuleResultOuterClass.RuleDescription, proto.RuleResultOuterClass.RuleDescription.Builder, proto.RuleResultOuterClass.RuleDescriptionOrBuilder>(
                  getRuleDescription(),
                  getParentForChildren(),
                  isClean());
          ruleDescription_ = null;
        }
        return ruleDescriptionBuilder_;
      }

      private boolean ruleApplies_ ;
      /**
       * <code>bool rule_applies = 2;</code>
       */
      public boolean getRuleApplies() {
        return ruleApplies_;
      }
      /**
       * <code>bool rule_applies = 2;</code>
       */
      public Builder setRuleApplies(boolean value) {
        
        ruleApplies_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool rule_applies = 2;</code>
       */
      public Builder clearRuleApplies() {
        
        ruleApplies_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.RuleResult)
    }

    // @@protoc_insertion_point(class_scope:proto.RuleResult)
    private static final proto.RuleResultOuterClass.RuleResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RuleResultOuterClass.RuleResult();
    }

    public static proto.RuleResultOuterClass.RuleResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RuleResult>
        PARSER = new com.google.protobuf.AbstractParser<RuleResult>() {
      public RuleResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RuleResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RuleResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RuleResult> getParserForType() {
      return PARSER;
    }

    public proto.RuleResultOuterClass.RuleResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RuleDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RuleDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
     */
    int getRuleTypeValue();
    /**
     * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
     */
    proto.RuleResultOuterClass.RuleDescription.RuleType getRuleType();

    /**
     * <code>string rule_explanation = 2;</code>
     */
    java.lang.String getRuleExplanation();
    /**
     * <code>string rule_explanation = 2;</code>
     */
    com.google.protobuf.ByteString
        getRuleExplanationBytes();
  }
  /**
   * Protobuf type {@code proto.RuleDescription}
   */
  public  static final class RuleDescription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.RuleDescription)
      RuleDescriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RuleDescription.newBuilder() to construct.
    private RuleDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RuleDescription() {
      ruleType_ = 0;
      ruleExplanation_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RuleDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              ruleType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ruleExplanation_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RuleResultOuterClass.internal_static_proto_RuleDescription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RuleResultOuterClass.internal_static_proto_RuleDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RuleResultOuterClass.RuleDescription.class, proto.RuleResultOuterClass.RuleDescription.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.RuleDescription.RuleType}
     */
    public enum RuleType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OPINION = 0;</code>
       */
      OPINION(0),
      /**
       * <code>FACT = 1;</code>
       */
      FACT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OPINION = 0;</code>
       */
      public static final int OPINION_VALUE = 0;
      /**
       * <code>FACT = 1;</code>
       */
      public static final int FACT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RuleType valueOf(int value) {
        return forNumber(value);
      }

      public static RuleType forNumber(int value) {
        switch (value) {
          case 0: return OPINION;
          case 1: return FACT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RuleType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RuleType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RuleType>() {
              public RuleType findValueByNumber(int number) {
                return RuleType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.RuleResultOuterClass.RuleDescription.getDescriptor().getEnumTypes().get(0);
      }

      private static final RuleType[] VALUES = values();

      public static RuleType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RuleType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.RuleDescription.RuleType)
    }

    public static final int RULE_TYPE_FIELD_NUMBER = 1;
    private int ruleType_;
    /**
     * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
     */
    public int getRuleTypeValue() {
      return ruleType_;
    }
    /**
     * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
     */
    public proto.RuleResultOuterClass.RuleDescription.RuleType getRuleType() {
      proto.RuleResultOuterClass.RuleDescription.RuleType result = proto.RuleResultOuterClass.RuleDescription.RuleType.valueOf(ruleType_);
      return result == null ? proto.RuleResultOuterClass.RuleDescription.RuleType.UNRECOGNIZED : result;
    }

    public static final int RULE_EXPLANATION_FIELD_NUMBER = 2;
    private volatile java.lang.Object ruleExplanation_;
    /**
     * <code>string rule_explanation = 2;</code>
     */
    public java.lang.String getRuleExplanation() {
      java.lang.Object ref = ruleExplanation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleExplanation_ = s;
        return s;
      }
    }
    /**
     * <code>string rule_explanation = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRuleExplanationBytes() {
      java.lang.Object ref = ruleExplanation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleExplanation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ruleType_ != proto.RuleResultOuterClass.RuleDescription.RuleType.OPINION.getNumber()) {
        output.writeEnum(1, ruleType_);
      }
      if (!getRuleExplanationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleExplanation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ruleType_ != proto.RuleResultOuterClass.RuleDescription.RuleType.OPINION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, ruleType_);
      }
      if (!getRuleExplanationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleExplanation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RuleResultOuterClass.RuleDescription)) {
        return super.equals(obj);
      }
      proto.RuleResultOuterClass.RuleDescription other = (proto.RuleResultOuterClass.RuleDescription) obj;

      boolean result = true;
      result = result && ruleType_ == other.ruleType_;
      result = result && getRuleExplanation()
          .equals(other.getRuleExplanation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RULE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + ruleType_;
      hash = (37 * hash) + RULE_EXPLANATION_FIELD_NUMBER;
      hash = (53 * hash) + getRuleExplanation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RuleResultOuterClass.RuleDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RuleDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RuleDescription)
        proto.RuleResultOuterClass.RuleDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleDescription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RuleResultOuterClass.RuleDescription.class, proto.RuleResultOuterClass.RuleDescription.Builder.class);
      }

      // Construct using proto.RuleResultOuterClass.RuleDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ruleType_ = 0;

        ruleExplanation_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleDescription_descriptor;
      }

      public proto.RuleResultOuterClass.RuleDescription getDefaultInstanceForType() {
        return proto.RuleResultOuterClass.RuleDescription.getDefaultInstance();
      }

      public proto.RuleResultOuterClass.RuleDescription build() {
        proto.RuleResultOuterClass.RuleDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RuleResultOuterClass.RuleDescription buildPartial() {
        proto.RuleResultOuterClass.RuleDescription result = new proto.RuleResultOuterClass.RuleDescription(this);
        result.ruleType_ = ruleType_;
        result.ruleExplanation_ = ruleExplanation_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RuleResultOuterClass.RuleDescription) {
          return mergeFrom((proto.RuleResultOuterClass.RuleDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RuleResultOuterClass.RuleDescription other) {
        if (other == proto.RuleResultOuterClass.RuleDescription.getDefaultInstance()) return this;
        if (other.ruleType_ != 0) {
          setRuleTypeValue(other.getRuleTypeValue());
        }
        if (!other.getRuleExplanation().isEmpty()) {
          ruleExplanation_ = other.ruleExplanation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RuleResultOuterClass.RuleDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RuleResultOuterClass.RuleDescription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int ruleType_ = 0;
      /**
       * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
       */
      public int getRuleTypeValue() {
        return ruleType_;
      }
      /**
       * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
       */
      public Builder setRuleTypeValue(int value) {
        ruleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
       */
      public proto.RuleResultOuterClass.RuleDescription.RuleType getRuleType() {
        proto.RuleResultOuterClass.RuleDescription.RuleType result = proto.RuleResultOuterClass.RuleDescription.RuleType.valueOf(ruleType_);
        return result == null ? proto.RuleResultOuterClass.RuleDescription.RuleType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
       */
      public Builder setRuleType(proto.RuleResultOuterClass.RuleDescription.RuleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        ruleType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.RuleDescription.RuleType rule_type = 1;</code>
       */
      public Builder clearRuleType() {
        
        ruleType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ruleExplanation_ = "";
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public java.lang.String getRuleExplanation() {
        java.lang.Object ref = ruleExplanation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ruleExplanation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRuleExplanationBytes() {
        java.lang.Object ref = ruleExplanation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ruleExplanation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public Builder setRuleExplanation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ruleExplanation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public Builder clearRuleExplanation() {
        
        ruleExplanation_ = getDefaultInstance().getRuleExplanation();
        onChanged();
        return this;
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public Builder setRuleExplanationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ruleExplanation_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.RuleDescription)
    }

    // @@protoc_insertion_point(class_scope:proto.RuleDescription)
    private static final proto.RuleResultOuterClass.RuleDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RuleResultOuterClass.RuleDescription();
    }

    public static proto.RuleResultOuterClass.RuleDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RuleDescription>
        PARSER = new com.google.protobuf.AbstractParser<RuleDescription>() {
      public RuleDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RuleDescription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RuleDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RuleDescription> getParserForType() {
      return PARSER;
    }

    public proto.RuleResultOuterClass.RuleDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RuleResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RuleResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RuleDescription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RuleDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/java/opinion/rules/RuleResult" +
      ".proto\022\005proto\"T\n\nRuleResult\0220\n\020rule_desc" +
      "ription\030\001 \001(\0132\026.proto.RuleDescription\022\024\n" +
      "\014rule_applies\030\002 \001(\010\"\202\001\n\017RuleDescription\022" +
      "2\n\trule_type\030\001 \001(\0162\037.proto.RuleDescripti" +
      "on.RuleType\022\030\n\020rule_explanation\030\002 \001(\t\"!\n" +
      "\010RuleType\022\013\n\007OPINION\020\000\022\010\n\004FACT\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_RuleResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RuleResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RuleResult_descriptor,
        new java.lang.String[] { "RuleDescription", "RuleApplies", });
    internal_static_proto_RuleDescription_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_RuleDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RuleDescription_descriptor,
        new java.lang.String[] { "RuleType", "RuleExplanation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
