// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/opinion/rules/RuleResult.proto

package proto;

public final class RuleResultOuterClass {
  private RuleResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RuleResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.RuleResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool ruled_passed = 1;</code>
     */
    boolean getRuledPassed();

    /**
     * <code>string rule_explanation = 2;</code>
     */
    java.lang.String getRuleExplanation();
    /**
     * <code>string rule_explanation = 2;</code>
     */
    com.google.protobuf.ByteString
        getRuleExplanationBytes();
  }
  /**
   * Protobuf type {@code proto.RuleResult}
   */
  public  static final class RuleResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.RuleResult)
      RuleResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RuleResult.newBuilder() to construct.
    private RuleResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RuleResult() {
      ruledPassed_ = false;
      ruleExplanation_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RuleResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              ruledPassed_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ruleExplanation_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.RuleResultOuterClass.internal_static_proto_RuleResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.RuleResultOuterClass.internal_static_proto_RuleResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.RuleResultOuterClass.RuleResult.class, proto.RuleResultOuterClass.RuleResult.Builder.class);
    }

    public static final int RULED_PASSED_FIELD_NUMBER = 1;
    private boolean ruledPassed_;
    /**
     * <code>bool ruled_passed = 1;</code>
     */
    public boolean getRuledPassed() {
      return ruledPassed_;
    }

    public static final int RULE_EXPLANATION_FIELD_NUMBER = 2;
    private volatile java.lang.Object ruleExplanation_;
    /**
     * <code>string rule_explanation = 2;</code>
     */
    public java.lang.String getRuleExplanation() {
      java.lang.Object ref = ruleExplanation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleExplanation_ = s;
        return s;
      }
    }
    /**
     * <code>string rule_explanation = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRuleExplanationBytes() {
      java.lang.Object ref = ruleExplanation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleExplanation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ruledPassed_ != false) {
        output.writeBool(1, ruledPassed_);
      }
      if (!getRuleExplanationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleExplanation_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ruledPassed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ruledPassed_);
      }
      if (!getRuleExplanationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleExplanation_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.RuleResultOuterClass.RuleResult)) {
        return super.equals(obj);
      }
      proto.RuleResultOuterClass.RuleResult other = (proto.RuleResultOuterClass.RuleResult) obj;

      boolean result = true;
      result = result && (getRuledPassed()
          == other.getRuledPassed());
      result = result && getRuleExplanation()
          .equals(other.getRuleExplanation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RULED_PASSED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRuledPassed());
      hash = (37 * hash) + RULE_EXPLANATION_FIELD_NUMBER;
      hash = (53 * hash) + getRuleExplanation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.RuleResultOuterClass.RuleResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.RuleResultOuterClass.RuleResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.RuleResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.RuleResult)
        proto.RuleResultOuterClass.RuleResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.RuleResultOuterClass.RuleResult.class, proto.RuleResultOuterClass.RuleResult.Builder.class);
      }

      // Construct using proto.RuleResultOuterClass.RuleResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ruledPassed_ = false;

        ruleExplanation_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.RuleResultOuterClass.internal_static_proto_RuleResult_descriptor;
      }

      public proto.RuleResultOuterClass.RuleResult getDefaultInstanceForType() {
        return proto.RuleResultOuterClass.RuleResult.getDefaultInstance();
      }

      public proto.RuleResultOuterClass.RuleResult build() {
        proto.RuleResultOuterClass.RuleResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.RuleResultOuterClass.RuleResult buildPartial() {
        proto.RuleResultOuterClass.RuleResult result = new proto.RuleResultOuterClass.RuleResult(this);
        result.ruledPassed_ = ruledPassed_;
        result.ruleExplanation_ = ruleExplanation_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.RuleResultOuterClass.RuleResult) {
          return mergeFrom((proto.RuleResultOuterClass.RuleResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.RuleResultOuterClass.RuleResult other) {
        if (other == proto.RuleResultOuterClass.RuleResult.getDefaultInstance()) return this;
        if (other.getRuledPassed() != false) {
          setRuledPassed(other.getRuledPassed());
        }
        if (!other.getRuleExplanation().isEmpty()) {
          ruleExplanation_ = other.ruleExplanation_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.RuleResultOuterClass.RuleResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.RuleResultOuterClass.RuleResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ruledPassed_ ;
      /**
       * <code>bool ruled_passed = 1;</code>
       */
      public boolean getRuledPassed() {
        return ruledPassed_;
      }
      /**
       * <code>bool ruled_passed = 1;</code>
       */
      public Builder setRuledPassed(boolean value) {
        
        ruledPassed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool ruled_passed = 1;</code>
       */
      public Builder clearRuledPassed() {
        
        ruledPassed_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object ruleExplanation_ = "";
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public java.lang.String getRuleExplanation() {
        java.lang.Object ref = ruleExplanation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ruleExplanation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRuleExplanationBytes() {
        java.lang.Object ref = ruleExplanation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ruleExplanation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public Builder setRuleExplanation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ruleExplanation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public Builder clearRuleExplanation() {
        
        ruleExplanation_ = getDefaultInstance().getRuleExplanation();
        onChanged();
        return this;
      }
      /**
       * <code>string rule_explanation = 2;</code>
       */
      public Builder setRuleExplanationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ruleExplanation_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.RuleResult)
    }

    // @@protoc_insertion_point(class_scope:proto.RuleResult)
    private static final proto.RuleResultOuterClass.RuleResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.RuleResultOuterClass.RuleResult();
    }

    public static proto.RuleResultOuterClass.RuleResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RuleResult>
        PARSER = new com.google.protobuf.AbstractParser<RuleResult>() {
      public RuleResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RuleResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RuleResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RuleResult> getParserForType() {
      return PARSER;
    }

    public proto.RuleResultOuterClass.RuleResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_RuleResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_RuleResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/java/opinion/rules/RuleResult" +
      ".proto\022\005proto\"<\n\nRuleResult\022\024\n\014ruled_pas" +
      "sed\030\001 \001(\010\022\030\n\020rule_explanation\030\002 \001(\tb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_RuleResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_RuleResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_RuleResult_descriptor,
        new java.lang.String[] { "RuledPassed", "RuleExplanation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
